swagger: '2.0'
info:
  version: 1.0.0
  title: Employees API
  contact:
    name: Apigee
    email: support@apigee.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: amer-poc8-prod.apigee.net
basePath: /v1
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /employees:
    get:
      summary: Get all Employees
      description: This endpoint returns a list of all Employees as an array.
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/EmployeesArray'
    post:
      summary: Create a new Employee
      description: This endpoint will create a new Employee.
      parameters:
        - name: body
          required: true
          description: an Employee oject
          in: body
          schema:
            $ref: '#/definitions/Employee'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Employee'
  /employees/{employee-uuid}:
    get:
      summary: Get an Employee with given UUID
      description: This endpoint returns an Employee.
      parameters:
        - name: employee-uuid
          in: path
          required: true
          description: UUID of an Employee
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Employee'
    put:
      summary: Update an Employee with given UUID
      description: This endpoint will update an existing Employee.
      parameters:
        - name: employee-uuid
          in: path
          required: true
          description: UUID of a Employee
          type: string
        - name: body
          required: true
          description: an Employee oject
          in: body
          schema:
            $ref: '#/definitions/Employee'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Employee'
    delete:
      summary: Delete an Employee with given UUID
      description: This endpoint will delete an existing Employee.
      parameters:
        - name: employee-uuid
          in: path
          required: true
          description: UUID of a Employee
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Employee'
definitions:
  EmployeesArray:
    type: array
    items:
      type: object
      properties:
        uuid:
          type: string
        name:
          type: string
        title:
          type: string
        email:
          type: string
        phone:
          type: string
  Employee:
    type: object
    properties:
      uuid:
        type: string
      name:
        type: string
      title:
        type: string
      email:
        type: string
      phone:
        type: string

